[package]
name = "ezpdb"
version = "0.7.0"
authors = ["Lander Brandt <landerbrandt@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/landaire/pdbview"
description = "High-level library for https://crates.io/crates/pdb"

[dependencies]
ms-pdb = { git = "https://github.com/microsoft/pdb-rs" }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
serde = { version = "1.0", features = ['derive', 'rc'], optional = true }
uuid = "1.10"
zerocopy = { version = "0.8.14", features = ["alloc", "derive"] }
